# Generated by Django 3.2 on 2021-04-11 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210411_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='department',
        ),
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 19, 28, 38, 760425, tzinfo=utc)),
        ),
    ]
