# Generated by Django 3.2 on 2021-04-11 23:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210411_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 23, 3, 39, 786992, tzinfo=utc)),
        ),
    ]
