# Generated by Django 3.2 on 2021-04-11 23:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210411_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
        migrations.AlterField(
            model_name='blog',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 23, 5, 5, 933194, tzinfo=utc)),
        ),
    ]
